### ISSUE TITLE
Filter repo list: only show active repos

### ISSUE THREAD

**Issue by leo-unglaub** [maximtrp/droneci-vscode-extension#1]
Hey,
first of all, big thanks for your extension. It works perfectly, clean, fast and no bloat! Amazing!

One thing that i notices is, that the `Repos` list is quite long and it wold be nice if i could filter it to only show repos that are active for example.

Thanks and greetings
Leo

**Comment by maximtrp** [comment]
Hey, Leo! Thank you! Yeah, nice suggestion! My list is long too, so I have been thinking recently about filtering and sorting repos :-) Will implement it in the next version

**Comment by leo-unglaub** [comment]
I saw that you implemented some filters for the repos. Thats amazing, thanks. The only thing i noticed is, that after the update the repository list was empty because the default filter was falling back to nothing. Only after setting a filter it started working, maybe some wrong default value somewhere? 

But since this only happened after an update, its propobly not that big of an issue.

**Comment by maximtrp** [comment]
Thank you! Tried to improve default filters behavior.

**Comment by leo-unglaub** [comment]
Improvements work great, much easier to work with now! Amazing work, big thanks!

**Comment by maximtrp** [comment]
Glad it helped! Thank you for suggestions and reporting!
