### ISSUE TITLE
Set a default server

### ISSUE THREAD

**Issue by leo-unglaub** [maximtrp/droneci-vscode-extension#2]
Hey,
its amazing that you have support for multiple servers. But in my case i only have one and i would be nice if i could define one server as a default thats gets connected to automatically. That way it saves a few clicks every time i am opening your extension.

Would that be possible?
Thanks and greetings
Leo

**Comment by maximtrp** [comment]
Hi! Thank you again! I guess it is not difficult. Will try to add this feature soon

**Comment by maximtrp** [comment]
Just published the new version. Please check if it is working for you

**Comment by leo-unglaub** [comment]
I give this version a try and for me it does not work. I have one server configured, but every time i open the panel i have to click the server manually before the repository list is loaded.

I also tried re-adding the server to see if that fixes it, but no. Is there a config option i have to set for this to work?

**Comment by maximtrp** [comment]
Thank you for the feedback! I hope I have finally fixed it in the latest version (v2.0). Please test it again

**Comment by leo-unglaub** [comment]
Works perfectly now. Big thanks! :+1:
