### ISSUE TITLE
Cannot connect to the drone instance

### ISSUE THREAD

**Issue by smnbbrv** [maximtrp/droneci-vscode-extension#4]
Hi,

thank you for your extension!

Unfortunately I cannot login into my self-hosted drone server

<img width="477" alt="image" src="https://github.com/maximtrp/droneci-vscode-extension/assets/13453858/eb737ea4-366b-4cfe-8642-c219953074ec">

The server is totally fine, publically accessible and has a valid certificate. The token I use is the personal token that I got in the UI

Could you provide some hints why this could happen? 

Thanks!

**Comment by maximtrp** [comment]
Hey! Thank you for reporting! I need more details to help you: 1) your versions of VSCode and extension, 2) your environment (web?), 3) will you be able to debug the extension?

**Comment by smnbbrv** [comment]
Hi

1. the version of VSCode: 1.85.1, extension: v2.0.0
2. macos
3. sure, however wanted to avoid it :) seems like it is inevitable. I'll check what I can find there

**Comment by smnbbrv** [comment]
Actually I get 403 on this line

https://github.com/maximtrp/droneci-vscode-extension/blob/c54a9fefeeea5d586858aed4edd56bbf672b56de/src/repos.ts#L54

However if I change `getRepos` to `selfRepos`, it seems the extension works as expected.

My drone instanse is quite restricted by the organization and members, that's probably the reason the original flow does not work.

I'm totally unsure if `selfRepos` is not breaking another (e.g. your) drone setup. Could you check if this can be used instead of `getRepos`?

**Comment by maximtrp** [comment]
Perfect! Thank you! Fixed in the latest release. This API seems preferrable based on the official documentation.

**Comment by smnbbrv** [comment]
Thanks! Works as expected now :)
